{
 "title": "Validator stats",
 "time": { "from": "now-65m", "to": "now-55m" },
 "refresh": "10s",
 "panels": [
  { "title": "Osmosis stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "APR",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "75000000/exporter_bondedTokens{instance=\"localhost:26661\",job=\"cosmosie\"}*100000000"
    }
   ]
  },
  {
   "title": "Total amount of bonded Osmosis",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "exporter_bondedTokens{instance=\"localhost:26661\",job=\"cosmosie\"}/1000000"
    }
   ]
  },
  {
   "title": "Total bonded ratio",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(exporter_bondedTokens{instance=\"localhost:26661\",job=\"cosmosie\"}/1000000)/(exporter_totalSupply{instance=\"localhost:26661\",job=\"cosmosie\"}/1000000 - 215958904 - 9041096)*100"
    }
   ]
  },
  {
   "title": "Total amount of unbonded  Osmosis",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "exporter_totalSupply{instance=\"localhost:26661\",job=\"cosmosie\"}/1000000 - 215958904 - 9041096 - exporter_bondedTokens{instance=\"localhost:26661\",job=\"cosmosie\"}/1000000"
    }
   ]
  },
  {
   "title": "Total unbonded ratio",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100-(exporter_bondedTokens{instance=\"localhost:26661\",job=\"cosmosie\"}/1000000)/(exporter_totalSupply{instance=\"localhost:26661\",job=\"cosmosie\"}/1000000 - 215958904 - 9041096)*100"
    }
   ]
  },
  {
   "title": "Total  Osmosis supply",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "exporter_totalSupply{instance=\"localhost:26661\",job=\"cosmosie\"}/1000000 - 215958904 - 9041096"
    }
   ]
  },
  {
   "title": "Community Pool",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 5, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "OSMO_POOL_total{instance=\"localhost:8000\",v=\"osmo_community_pool\"}/1000000"
    }
   ]
  },
  {
   "title": "Osmo Price",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 11, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "OSMO_PRICE_total{instance=\"localhost:8000\",job=\"osmo_price\"}"
    }
   ]
  },
  {
   "title": "Active proposals",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "OSMO_GOV_OPEN_PROPOSALS_total{instance=\"localhost:8000\",v=\"osmo_gov_open\"}"
    }
   ]
  },
  {
   "title": "Pending proposals",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "OSMO_GOV_DEPOST_PROPOSALS{instance=\"localhost:8000\",v=\"osmo_gov_deposit\"}"
    }
   ]
  },
  {
   "title": "Latest block height",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "exporter_blockHeight{instance=\"localhost:26661\",job=\"cosmosie\"}\t"
    }
   ]
  },
  {
   "title": "Current block time",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 5, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "tendermint_consensus_block_interval_seconds_sum{instance=\"localhost:26660\",chain_id=\"osmosis-1\"}/tendermint_consensus_block_interval_seconds_count{instance=\"localhost:26660\",chain_id=\"osmosis-1\"}",
     "legendFormat": "Block time"
    }
   ]
  },
  {
   "title": "Total Transactions",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 11, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "OSMO_TRX_COUNT{}" }
   ]
  },
  {
   "title": "Transactions per block",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "tendermint_consensus_num_txs" }
   ]
  },
  { "title": "Validator Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Bro_n_Bro validator status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "exporter_jailStatus{instance=\"localhost:26661\",job=\"cosmosie\"}"
    }
   ]
  },
  {
   "title": "Bro_n_Bro commission rate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "exporter_commissionRate{instance=\"localhost:26661\",job=\"cosmosie\"}"
    }
   ]
  },
  {
   "title": "Bro_n_Bro: staked Osmosis",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "exporter_delegationShares{instance=\"localhost:26661\",job=\"cosmosie\"}/1000000*0.999800011"
    }
   ]
  },
  {
   "title": "Accumalated reward balance",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "exporter_commission_uosmo{instance=\"localhost:26661\",job=\"cosmosie\"}/1000000"
    }
   ]
  },
  {
   "title": "Bro_n_Bro pre-commit status",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "exporter_precommitStatus{instance=\"localhost:26661\",job=\"cosmosie\"}",
     "legendFormat": "Validator precomit"
    }
   ]
  }
 ]
}